<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Dashboard</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div>
          </div>
          <center>
              <form method="post" action="#" name="bet">
                  <div class="row">
                      <div class="col-3">
                          <button type="button" class="btn btn-primary btn-lg">Minimo</button>
                      </div>
                      <div class="col-3">
                          <button type="button" class="btn btn-primary btn-lg">Maximo</button>
                      </div>
                      <div class="col-3">
                          <button type="button" class="btn btn-primary btn-lg">Bet Low</button>
                      </div>
                      <div class="col-3">
                          <button type="button" class="btn btn-primary btn-lg">Bet Low</button>
                      </div>
                      <div class="col-6">
                          <label for="inputEmail" class="sr-only">Bet Amount</label>
                          <input type="text" id="inputEmail" class="form-control" name="amount" placeholder="Bet Amount" required autofocus>
                      </div>
                      <div class="col-6">
                          <label for="inputEmail" class="sr-only">% Win chance</label>
                          <input type="text" id="inputEmail" name="percent" class="form-control" placeholder="% Win"  value="49.95" required autofocus>
                      </div>
                      <div class="col-12">
                          <?php echo $this->result?>
                          <p>BTC <?php echo $this->BTC ?>
                          </p>
                      </div>
                  
                      <div class="col-6">
                          <p>0 - 499499
                          </p><button type="submit" name="bet_low" class="btn btn-primary btn-lg btn-block">Bet Low</button>
                      </div>
                      <div class="col-6">
                          <p>500500 - 999999
                          </p><button type="submit" name="bet_high" class="btn btn-secondary btn-lg btn-block">Bet High</button>
                      </div>    
                  </div>
              </form>
          </center>    
          <h2>Bets</h2>
          
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Bet</th>
                  <th>Amount</th>
                  <th>Type</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
  </body>
 
