
          <tr>
            <td valign="top" width="250">&nbsp;</td>
          </tr>
          <tr>
            <td valign="top" width="250">&nbsp;</td>
          </tr>
        </tbody></table></td>
        <td width="700"><table align="center" border="0" cellpadding="0" cellspacing="0" width="680">
          <tbody><tr>
            <td height="25" valign="top" width="680">&nbsp;</td>
          </tr>
          <tr>
            <td class="head-1" height="25" valign="top" width="680">Welcome to Ultimate Casino</td>
          </tr>
          <tr>
            <td valign="top" width="680">&nbsp;</td>
          </tr>
          <tr>
            <td valign="top" width="680"><table border="0" cellpadding="0" cellspacing="0" width="680">
              <tbody><tr valign="middle">
                <td width="200"><img src="<?php echo $this->basePath('theme/Shadow/images/pic1.jpg')?>" height="122" width="183"></td>
                <td class="txt-2" width="480">Lorem ipsum dolor sit
amet, consectetur adipiscing elit. Nullam in mauris at sem mattis elemen
 tum. Etiam erat nunc, venenatis quis ultrices vulputate, iaculis ac
odio. Nullam non laoreet sa pien. Morbi adipisc rej ing, lacus non
tempus porta, ligula tellus pulvinar neque, a sodales ligula nisl eget
augue.
                  <p>Aliquam cursus, lorem vitae blandit lobortis, felis
 mi laoreet arcu, ac vehicula ligula elit nec mau ris. Integ er quis
mauris sed odio fermentum porttitor in ac orci. Morbi vel felis metus,
non vari us est. Nunc venen atis, diam ut facilisis suscipit, sapien
felis vulputate erat, sedgna diam vel mauris. </p></td>
              </tr>
            </tbody></table></td>
          </tr>
          <tr>
            <td valign="top" width="680">&nbsp;</td>
          </tr>
          <tr>
            <td valign="top" width="680">&nbsp;</td>
          </tr>
          <tr>
            <td class="head-1" valign="top" width="680">Top Casinos</td>
          </tr>
          <tr>
            <td valign="top" width="680">&nbsp;</td>
          </tr>
          <tr>
            <td valign="top" width="680"><table align="center" border="0" cellpadding="0" cellspacing="0" width="680">
              <tbody><tr>
                <td style="background-repeat:repeat-x;" background="<?php echo $this->basePath('theme/Shadow/images/cntr_bg.jpg')?>" height="110" valign="middle" width="680"><table align="center" border="0" cellpadding="0" cellspacing="0" width="640">
                  <tbody><tr valign="top">
                    <td width="480"><table border="0" cellpadding="0" cellspacing="0" width="480">
                      <tbody><tr>
                        <td class="head-4" height="30" valign="middle" width="480">Casino Name</td>
                      </tr>
                      <tr>
                        <td class="txt-3" height="30" valign="top" width="480">Lorem
 ipsum dolor sit amet, consectetur adipiscing elit. Nullam in mauris at
sem mattis elemen uno fermen tum porttitor in ac orci. Morbi vel felis
me tus, non vari us est. Nunc venen tum. Etiam erat nunc, venen atis
ltrices vulpu tate, iaculis ac odio. Nullam non lao reet re sapien.
Morbi adipiscing.</td>
                      </tr>
                    </tbody></table></td>
                    <td align="center" width="160"><a href="#"><img src="<?php echo $this->basePath('theme/Shadow/images/pic2.jpg')?>" border="0" height="85" width="128"></a></td>
                  </tr>
                </tbody></table></td>
              </tr>
            </tbody></table></td>
          </tr>
          <tr>
            <td valign="top" width="680">&nbsp;</td>
          </tr>
		  <tr>
            <td valign="top" width="680"><table align="center" border="0" cellpadding="0" cellspacing="0" width="680">
              <tbody><tr>
                <td style="background-repeat:repeat-x;" background="<?php echo $this->basePath('theme/Shadow/images/cntr_bg.jpg')?>" height="110" valign="middle" width="680"><table align="center" border="0" cellpadding="0" cellspacing="0" width="640">
                    <tbody><tr valign="top">
                      <td width="480"><table border="0" cellpadding="0" cellspacing="0" width="480">
                          <tbody><tr>
                            <td class="head-4" height="30" valign="middle" width="480">Casino Name</td>
                          </tr>
                          <tr>
                            <td class="txt-3" height="30" valign="top" width="480">Lorem
 ipsum dolor sit amet, consectetur adipiscing elit. Nullam in mauris at
sem mattis elemen uno fermen tum porttitor in ac orci. Morbi vel felis
me tus, non vari us est. Nunc venen tum. Etiam erat nunc, venen atis
ltrices vulpu tate, iaculis ac odio. Nullam non lao reet re sapien.
Morbi adipiscing.</td>
                          </tr>
                      </tbody></table></td>
                      <td align="center" width="160"><a href="#"><img src="<?php echo $this->basePath('theme/Shadow/images/pic2.jpg')?>" border="0" height="85" width="128"></a></td>
                    </tr>
                </tbody></table></td>
              </tr>
            </tbody></table></td>
          </tr>
		  <tr>
            <td valign="top" width="680">&nbsp;</td>
          </tr>
		  <tr>
            <td valign="top" width="680"><table align="center" border="0" cellpadding="0" cellspacing="0" width="680">
              <tbody><tr>
                <td style="background-repeat:repeat-x;" background="<?php echo $this->basePath('theme/Shadow/images/cntr_bg.jpg')?>" height="110" valign="middle" width="680"><table align="center" border="0" cellpadding="0" cellspacing="0" width="640">
                    <tbody><tr valign="top">
                      <td width="480"><table border="0" cellpadding="0" cellspacing="0" width="480">
                          <tbody><tr>
                            <td class="head-4" height="30" valign="middle" width="480">Casino Name</td>
                          </tr>
                          <tr>
                            <td class="txt-3" height="30" valign="top" width="480">Lorem
 ipsum dolor sit amet, consectetur adipiscing elit. Nullam in mauris at
sem mattis elemen uno fermen tum porttitor in ac orci. Morbi vel felis
me tus, non vari us est. Nunc venen tum. Etiam erat nunc, venen atis
ltrices vulpu tate, iaculis ac odio. Nullam non lao reet re sapien.
Morbi adipiscing.</td>
                          </tr>
                      </tbody></table></td>
                      <td align="center" width="160"><a href="#"><img src="<?php echo $this->basePath('theme/Shadow/images/pic2.jpg')?>" border="0" height="85" width="128"></a></td>
                    </tr>
                </tbody></table></td>
              </tr>
            </tbody></table></td>
          </tr>
		  <tr>
            <td valign="top" width="680">&nbsp;</td>
          </tr>
		  <tr>
            <td valign="top" width="680">&nbsp;</td>
          </tr>
        </tbody></table></td>
      </tr>
    </tbody></table></td>
  </tr>
  <tr>
    <td valign="top" width="980"><table border="0" cellpadding="0" cellspacing="0" width="980">
      <tbody><tr>
        <td style="background-repeat:repeat-x;" background="<?php echo $this->basePath('theme/Shadow/images/ftr_bg.jpg')?>" height="45" valign="top" width="980"><table align="center" border="0" cellpadding="0" cellspacing="0" width="650">
          <tbody><tr valign="top">
            <td align="center" valign="middle" width="88"><a href="#" class="navbar2">Home</a></td>
            <td width="5"><img src="<?php echo $this->basePath('theme/Shadow/images/ftr_dvd.jpg')?>" height="45" width="5"></td>
            <td align="center" valign="middle" width="88"><a href="#" class="navbar2">Link 1</a></td>
            <td width="5"><img src="<?php echo $this->basePath('theme/Shadow/images/ftr_dvd.jpg')?>" height="45" width="5"></td>
            <td align="center" valign="middle" width="88"><a href="#" class="navbar2">Link 2</a></td>
            <td width="5"><img src="<?php echo $this->basePath('theme/Shadow/images/ftr_dvd.jpg')?>" height="45" width="5"></td>
            <td align="center" valign="middle" width="88"><a href="#" class="navbar2">Link 3</a></td>
            <td width="5"><img src="<?php echo $this->basePath('theme/Shadow/images/ftr_dvd.jpg')?>" height="45" width="5"></td>
            <td align="center" valign="middle" width="88"><a href="#" class="navbar2">Link 4</a></td>
            <td width="5"><img src="<?php echo $this->basePath('theme/Shadow/images/ftr_dvd.jpg')?>" height="45" width="5"></td>
            <td align="center" valign="middle" width="88"><a href="#" class="navbar2">Link 5</a></td>
            <td width="5"><img src="<?php echo $this->basePath('theme/Shadow/images/ftr_dvd.jpg')?>" height="45" width="5"></td>
            <td align="center" valign="middle" width="92"><a href="#" class="navbar2">Contact</a></td>
          </tr>
        </tbody></table></td>
      </tr>
      <tr>
        <td class="txt-2" align="center" height="60" valign="middle"><br>

