<?php echo $this->headLink()->prependStylesheet($this->basePath('theme/Bootstrap/signin.css'))
?>
<body class="text-center">
    <form class="form-signin" method="POST" name="signup">
      <img class="mb-4" src="../../assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Signup</h1>
      <label for="inputUser" class="sr-only">User</label>
      <input type="text" id="inputUser" class="form-control"  name="user" placeholder="Username" required autofocus>
      <label for="inputEmail" class="sr-only">Email address</label>
      <input type="email" id="inputEmail" class="form-control" name="email" placeholder="Email address" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" class="form-control" name="password" placeholder="Password" required>
      <label for="repeatPassword" class="sr-only">Repeat Password</label>
      <input type="password" id="repeatPassword" class="form-control" name="password2" placeholder="Password Again" required autofocus>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit" name="signup">Sign up</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
  </body>
</html>
