<form method="POST" class="form-signin">
  <img class="mb-4" src="{{ site.baseurl }}/docs/{{ site.docs_version }}/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
  <?php echo var_dump($this->form)?>
  <h1 class="h3 mb-3 font-weight-normal">Sign up</h1>
  <div class="form-label-group">
    <input type="text" id="inputName" name="name" class="form-control" placeholder="Name" required autofocus>
    <label for="inputName"></label>
  </div>

  <div class="form-label-group">
    <input type="text" id="inputUser" name="user" class="form-control" placeholder="User" required>
    <label for="inputUser"></label>
  </div>
  
  <div class="form-label-group">
    <input type="email" id="inputEmail" name="email" class="form-control" placeholder="Email address" required autofocus>
    <label for="inputEmail"></label>
  </div>
  
  <div class="form-label-group">
    <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required autofocus>
    <label for="inputPassword"></label>
  </div>
  
  <div class="form-label-group">
    <input type="password" id="inputPassword2" name="password2" class="form-control" placeholder="Repeat Password" required autofocus>
    <label for="inputPassword2"></label>
  </div>

  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
 <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
</form>