<!-- footer content -->

    

   
    <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('theme/Gentelella/build/js/custom.min.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/bootstrap-daterangepicker/daterangepicker.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/moment/min/moment.min.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/DateJS/build/date.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/flot.curvedlines/curvedLines.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/flot-spline/js/jquery.flot.spline.min.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/flot.orderbars/js/jquery.flot.orderBars.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/Flot/jquery.flot.resize.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/Flot/jquery.flot.stack.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/Flot/jquery.flot.time.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/Flot/jquery.flot.pie.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/Flot/jquery.flot.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/skycons/skycons.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/gauge.js/dist/gauge.min.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/morris.js/morris.min.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/raphael/raphael.min.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/jquery-sparkline/dist/jquery.sparkline.min.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/Chart.js/dist/Chart.min.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/nprogress/nprogress.js'))
            ->prependFile($this->basePath('../vendor/bootstrap/dist/js/vendor/popper.min.js'))
            ->prependFile($this->basePath('../vendor/bootstrap/dist/js/bootstrap.min.js'))
            ->prependFile($this->basePath('theme/Gentelella/vendors/jquery/dist/jquery.min.js'))
       ?>


  </body>
</html>