<?php echo $this->doctype() ?>

<html lang="en">
    <head>
    <title><?php echo $app->getTitle('name')?></title>
    <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('../vendor/bootstrap/dist/css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('theme/Bootstrap/dashboard.css'))
            ->prependStylesheet($this->basePath('theme/Gentelella/vendors/font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('theme/Gentelella/vendors/nprogress/nprogress.css'))
            ->prependStylesheet($this->basePath('theme/Gentelella/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css'))
            ->prependStylesheet($this->basePath('theme/Gentelella/vendors/vendors/bootstrap-daterangepicker/daterangepicker.css'))
            ->prependStylesheet($this->basePath('theme/Gentelella/build/css/custom.min.css'))
            ->prependStylesheet($this->basePath('theme/Bootstrap/grid.css'))
            
        ?>
  </head>
<body>
    <nav class="navbar navbar-expand-xl fixed-top navbar-dark bg-dark">
      <a class="navbar-brand" href="#"><?php echo $app->getTitle('name');?></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample06" aria-controls="navbarsExample06" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample06">
        
        
      </div>
      <div class="collapse navbar-collapse" id="navbarsExample06">
        
        
      </div>
      
    
    
    <?php if($user != null){ ?>
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="#"><?php echo $user?></a>
        </li>
      </ul>
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="#">Sign out</a>
        </li>
      </ul>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <?php foreach($sidebar as $key){?><li class="nav-item">
                <a class="nav-link active" href="#">
                  <span data-feather="<?php echo $key['img-code']?>"></span>
                  <?php echo $key['name']?> <span class="sr-only">(current)</span>
                </a>
              </li>
              <?php }?>
           
            </ul>

            
          </div>
        </nav>
        <?php } ?>
        </nav>   <!-- /top navigation -->

