<script src="<?php echo $this->basePath('charts/Chart.js/moment.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->basePath('charts/Chart.js/Chart.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->basePath('charts/Chart.js/Chart.Financial.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->basePath('charts/Chart.js/utils.js')?>" type="text/javascript"></script>

<div style="width:1550px">
			<canvas id="chart1" width="800" height="400"></canvas>
		</div>
<script>
        var dateFormat = 'MMMM DD YYYY';
        var date = moment();
		var data = getRandomData('April 01 10', 5);
		/*[
		    {
		    	
		        o: 136.65,
		        h: 136.96,
		        l: 134.15,
		        c: 136.49,
		        value: 300, color:"#F7464A", highlight: "#FF5A5E", label: "Red"
		    },
		    {
		    	
		        o: 34.65,
		        h: 236.96,
		        l: 45.15,
		        c: 136.49,
		        value: 300, color:"#F7464A", highlight: "#FF5A5E", label: "Red"
		    }
		];*/        
		//document.write(data);
		// Candlestick
		var ctx = document.getElementById("chart1").getContext("2d");
		ctx.canvas.width = 1550;
		ctx.canvas.height = 700;
		new Chart(ctx, {
			type: 'candlestick',
			data: {
				datasets: [{
					label: "CHRT - Chart.js Corporation",
					data: data,
					fractionalDigitsCount: 2,
				}]
			},
			options: {
				tooltips: {
					position: 'nearest',
					mode: 'index',
				},
			},
		});
		// Custom Candlestick
		var ctx2 = document.getElementById("chart2").getContext("2d");
		ctx2.canvas.width = 1000;
		ctx2.canvas.height = 250;
		new Chart(ctx2, {
			type: 'candlestick',
			data: {
				datasets: [{
					color: {
						up: '#11f4',
						down: '#fb84',
						unchanged: '#999',
					},
					borderColor: '#000',
					borderWidth: 2,
					label: "CHRT - Chart.js Corporation",
					data: data
				}]
			}
		});
		// Longer tooltip
		var ctx3 = document.getElementById("chart3").getContext("2d");
		ctx3.canvas.width = 1000;
		ctx3.canvas.height = 250;
		new Chart(ctx3, {
			type: 'candlestick',
			data: {
				datasets: [{
					label: "CHRT - Chart.js Corporation",
					data: data,
					fractionalDigitsCount: 5,
				}]
			},
			options: {
				tooltips: {
					position: 'nearest',
					mode: 'index',
				},
			},
		});
	</script>