
          <h2>Orders</h2>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Price Unitary</th>
                  <th>Amount <?php echo $_GET['amount_coin']?></th>
                  <th>Amount <?php echo $_GET['price_coin']?></th>
                  <th>Type</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach($this->orders as $key){?>
                      <tr>
                          <td><?php echo $key['id']?></td>
                          <td><?php echo $key['price']?></td>
                          <td><?php echo $key['amount']?></td>
                          <td><?php if($_GET['amount_coin'] == $_GET['price_coin']){ echo $key['amount']; }else{echo $key['price'] * $key['amount'];}?></td>
                          <td><?php echo $key['type']?></td>
                          <td><?php echo $key['status']?></td>
                          <td>
                              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Open modal for @getbootstrap</button>
                    
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                  <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                        </button>
                                      </div>
                                      <div class="modal-body">
                                        <form>
                                          <div class="form-group">
                                            <label for="recipient-name" class="col-form-label">Recipient:</label>
                                            <input type="text" class="form-control" id="recipient-name">
                                          </div>
                                          <div class="form-group">
                                            <label for="message-text" class="col-form-label">Message:</label>
                                            <textarea class="form-control" id="message-text"></textarea>
                                          </div>
                                        </form>
                                      </div>
                                      <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="button" class="btn btn-primary">Send message</button>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                        </td> 
                     </tr>
                <?php } ?>
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>

   