

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">My Wallet <?php echo $this->balance?></h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div>
          </div>
            <?php echo $this->userToDeposit?>
                                                      
          <!--  <div id="mainb" style="height:350px;"></div>-->
        
           <div class="row">
              <div class="col-sm-6">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Deposit</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Profit Investor Deposit </button>
                    
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                  <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">New Deposit</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                        </button>
                                      </div>
                                      <div class="modal-body">
                                        <form name="buy" action="" method="POST">
                                          <div class="form-group">
                                            <label for="recipient-name" class="col-form-label">Deposit Value:</label>
                                            <input type="text" id="inputAmount" name="amount" class="form-control" placeholder="Amount" required autofocus>
                                          </div>
                                          <div class="form-group">
                                            <label for="message-text" class="col-form-label">Deposit Value:</label>
                                            <input type="text" id="inputPrice" name="price" class="form-control" placeholder="Price" required>
                                          </div>
                                          <div class="form-group">
                                            <label for="message-text" class="col-form-label">Deposit to:</label>
                                            <input type="text" class="form-control" id="message-text">
                                          </div>
                                          <div class="form-group">
                                            <label for="message-text" class="col-form-label">Total:</label>
                                            <input type="text" name="total" class="form-control" placeholder="Total" required>
                                          
                                          </div>
                                          
                                          <input type="hidden" name="amount_coin" class="form-control" value="BTC" required>
                                          <input type="hidden" name="type" class="form-control" value="buy" required>
                                          <input type="hidden" name="status" class="form-control" value="open" required>
                                          
                                          <input type="hidden" name="price_coin" class="form-control" value="BTC" required>
                                          
                                          <div class="modal-footer">
                                        	<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        	<button class="btn btn-lg btn-primary btn-block" type="submit">Buy</button>
                                          </div>
                                        </form>
                                      </div>
                                      
                                    </div>
                                  </div>
                                </div>
                  </div>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Withdraw</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#withdrawModal" data-whatever="@getbootstrap">Profit Withdraw </button>
                    
                                <div class="modal fade" id="withdrawModal" tabindex="-1" role="dialog" aria-labelledby="withdrawModalLabel" aria-hidden="true">
                                  <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <h5 class="modal-title" id="withdrawModalLabel">New Withdraw</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                        </button>
                                      </div>
                                      <div class="modal-body">
                                        <form name="sell" action="" method="POST">
                                          <div class="form-group">
                                            <label for="recipient-name" class="col-form-label">Withdraw Value:</label>
                                            <input type="text" id="inputAmount" name="amount" class="form-control" placeholder="Amount" required autofocus>
                                          </div>
                                          <div class="form-group">
                                            <label for="message-text" class="col-form-label">Withdraw Value:</label>
                                            <input type="text" id="inputPrice" name="price" class="form-control" placeholder="Price" required>
                                          </div>
                                          
                                          <div class="form-group">
                                            <label for="message-text" class="col-form-label">Total:</label>
                                            <input type="text" name="total" class="form-control" placeholder="Total" required>
                                          
                                          </div>
                                          
                                          <input type="hidden" name="amount_coin" class="form-control" value="BTC" required>
                                          <input type="hidden" name="type" class="form-control" value="sell" required>
                                          <input type="hidden" name="status" class="form-control" value="open" required>
                                          
                                          <input type="hidden" name="price_coin" class="form-control" value="BTC" required>
                                          
                                          <div class="modal-footer">
                                        	<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        	<button class="btn btn-lg btn-primary btn-block" type="submit">Withdraw</button>
                                          </div>
                                        </form>
                                      </div>
                                      
                                    </div>
                                  </div>
                                </div>
                  </div>
                </div>
              </div>
            </div>
          
          <h2>Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Coin</th>
                  <th>Balance</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach($this->balances as $key){?>
                      <tr>
                          <td><?php echo $key['id']?></td>
                          <td><?php echo $key['coin']?></td>
                          <td><?php echo $key['balance']?></td>
                          <td>
                              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Open modal for @getbootstrap</button>
                    
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                  <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                        </button>
                                      </div>
                                      <div class="modal-body">
                                        <form>
                                          <div class="form-group">
                                            <label for="recipient-name" class="col-form-label">Recipient:</label>
                                            <input type="text" class="form-control" id="recipient-name">
                                          </div>
                                          <div class="form-group">
                                            <label for="message-text" class="col-form-label">Message:</label>
                                            <textarea class="form-control" id="message-text"></textarea>
                                          </div>
                                        </form>
                                      </div>
                                      <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="button" class="btn btn-primary">Send message</button>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                        </td> 
                     </tr>
                <?php } ?>
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>

    