

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Dashboard </h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div>
          </div>
          <style type="text/css">/* Chart.js */
@-webkit-keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}@keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}.chartjs-render-monitor{-webkit-animation:chartjs-render-animation 0.001s;animation:chartjs-render-animation 0.001s;}</style>
          
          <div style="width: 100%; height: 90%; overflow: hidden;">
          <!--  <div id="mainb" style="height:350px;"></div>-->
         <iframe id="frame-spec" height="100%" width="100%" src="http://localhost/crowdforex/public/static/complete-candles"></iframe>
           </div>  <?php //echo $this->graphic?>
         
           
          
          <h2>Operator</h2>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th></th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <?php //foreach($this->balances as $key){?>
                      <tr>
                          <td><div class="row">
              <div class="col-sm-12">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Buy <?php echo $_GET['amount_coin']?></h5>
                       <p class="card-text">
                          <form name="buy" action="" method="POST">
                              <input type="text" id="inputAmount" name="amount" class="form-control" placeholder="Amount" required autofocus>
                              <input type="hidden" name="amount_coin" class="form-control" value="<?php echo $_GET['amount_coin']?>" required>
                              
                              <input type="text" id="inputPrice" name="price" class="form-control" placeholder="Price" required>
                              <input type="hidden" name="price_coin" class="form-control" value="<?php echo $_GET['price_coin']?>" required>
                              
                              <input type="text" name="total" class="form-control" placeholder="Total" required>
                              <input type="hidden" name="type" class="form-control" value="buy" required>
                              <input type="hidden" name="status" class="form-control" value="open" required>
                              
                              <button class="btn btn-lg btn-primary btn-block" type="submit">Buy</button>
                          </form>
                       </p>
                    
                  </div>
                </div>
              </div>
              </td>
              <td>
                  <div class="col-sm-12">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Stop Limit</h5>
                    <p class="card-text">
                          
                          <input type="text" id="inputAmount" name="amount" class="form-control" placeholder="Amount" required autofocus>
                          
                          <input type="text" id="inputPrice" name="price" class="form-control" placeholder="Price" required>
                          
                          <input type="text" name="total" class="form-control" placeholder="Total" required>
                          
                          <button class="btn btn-lg btn-primary btn-block" type="submit">Buy</button><button class="btn btn-lg btn-danger btn-block" type="submit">Sell</button>
                    </p>
                    
                  </div>
                </div>
              </div>
            </div>
              </td>
              <td>
              <div class="col-sm-12">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Sell <?php echo $_GET['amount_coin']?></h5>
                    <p class="card-text">
                          <form name="sell" action="" method="POST">
                              <input type="text" id="inputAmount" name="amount" class="form-control" placeholder="Amount" required autofocus>
                              <input type="hidden" name="amount_coin" class="form-control" value="<?php echo $_GET['amount_coin']?>" required>
                              
                              <input type="text" id="inputPrice" name="price" class="form-control" placeholder="Price" required>
                              <input type="hidden" name="price_coin" class="form-control" value="<?php echo $_GET['price_coin']?>" required>
                              
                              <input type="text" name="total" class="form-control" placeholder="Total" required>
                              <input type="hidden" name="type" class="form-control" value="sell" required>
                              <input type="hidden" name="status" class="form-control" value="open" required>
                              
                              <button class="btn btn-lg btn-danger btn-block" type="submit">Sell</button>
                          </form>
                       </p>
                    
                  </div>
                </div>
              </div>
            </div></td>
                          
                          
                     </tr>
                <?php //} ?>
              </tbody>
            </table>
          </div>
          <h2>Orders</h2>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Price Unitary</th>
                  <th>Amount <?php echo $_GET['amount_coin']?></th>
                  <th>Amount <?php echo $_GET['price_coin']?></th>
                  <th>Type</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach($this->orders as $key){?>
                      <tr>
                          <td><?php echo $key['id']?></td>
                          <td><?php echo $key['price']?></td>
                          <td><?php echo $key['amount']?></td>
                          <td><?php if($_GET['amount_coin'] == $_GET['price_coin']){ echo $key['amount']; }else{echo $key['price'] * $key['amount'];}?></td>
                          <td><?php echo $key['type']?></td>
                          <td><?php echo $key['status']?></td>
                          <td>
                              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Open modal for @getbootstrap</button>
                    
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                  <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                        </button>
                                      </div>
                                      <div class="modal-body">
                                        <form>
                                          <div class="form-group">
                                            <label for="recipient-name" class="col-form-label">Recipient:</label>
                                            <input type="text" class="form-control" id="recipient-name">
                                          </div>
                                          <div class="form-group">
                                            <label for="message-text" class="col-form-label">Message:</label>
                                            <textarea class="form-control" id="message-text"></textarea>
                                          </div>
                                        </form>
                                      </div>
                                      <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="button" class="btn btn-primary">Send message</button>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                        </td> 
                     </tr>
                <?php } ?>
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>

   