

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Dashboard </h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div>
          </div>
          
           
          
          
          <h2>Orders</h2>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Price Unitary</th>
                  <th>Amount <?php echo $_GET['amount_coin']?></th>
                  <th>Amount <?php echo $_GET['price_coin']?></th>
                  <th>Type</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach($this->orders as $key){?>
                      <tr>
                          <td><?php echo $key['id']?></td>
                          <td><?php echo $key['price']?></td>
                          <td><?php echo $key['amount']?></td>
                          <td><?php if($_GET['amount_coin'] == $_GET['price_coin']){ echo $key['amount']; }else{echo $key['price'] * $key['amount'];}?></td>
                          <td><?php echo $key['type']?></td>
                          <td><?php echo $key['status']?></td>
                          <td>
                             <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Profit Investor Deposit </button>
                    
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                  <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">New Deposit</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                        </button>
                                      </div>
                                      <div class="modal-body">
                                        <form name="approve" action="" method="POST">
                                          <div class="form-group">
                                            <label for="recipient-name" class="col-form-label">Id:</label>
                                            <input type="text" id="inputId" name="id" class="form-control" placeholder="Id" required autofocus>
                                          </div>
                                          
                                          
                                          <input type="hidden" name="amount_coin" class="form-control" value="BTC" required>
                                          <input type="hidden" name="type" class="form-control" value="buy" required>
                                          <input type="hidden" name="status" class="form-control" value="open" required>
                                          
                                          <input type="hidden" name="price_coin" class="form-control" value="BTC" required>
                                          
                                          <div class="modal-footer">
                                        	<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        	<button class="btn btn-lg btn-primary btn-block" type="submit">Approve</button>
                                          </div>
                                        </form>
                                      </div>
                                      
                                    </div>
                                  </div>
                                </div>
                        </td> 
                     </tr>
                <?php } ?>
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>

   